version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_DATABASE: cafe_app
      SPRING_DATA_MONGODB_URI: mongodb+srv://julianrojasgeo:VNQfwnAIipVmow2a@juliancluster.tmdnx7e.mongodb.net/cafe_app?retryWrites=true&w=majority